
ALTER TABLE `#__gridbox_pages` CHANGE `theme` `theme` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_pages` CHANGE `meta_title` `meta_title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_pages` CHANGE `meta_description` `meta_description` text;
ALTER TABLE `#__gridbox_pages` CHANGE `meta_keywords` `meta_keywords` text;
ALTER TABLE `#__gridbox_pages` CHANGE `params` `params` mediumtext;
ALTER TABLE `#__gridbox_pages` CHANGE `style` `style` mediumtext;
ALTER TABLE `#__gridbox_pages` CHANGE `fonts` `fonts` text;
ALTER TABLE `#__gridbox_pages` CHANGE `intro_image` `intro_image` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_pages` CHANGE `page_alias` `page_alias` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_pages` CHANGE `page_category` `page_category` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_pages` CHANGE `intro_text` `intro_text` mediumtext;
ALTER TABLE `#__gridbox_pages` CHANGE `image_alt` `image_alt` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_pages` CHANGE `share_title` `share_title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_pages` CHANGE `share_description` `share_description` text;
ALTER TABLE `#__gridbox_categories` CHANGE `title` `title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_categories` CHANGE `alias` `alias` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_categories` CHANGE `app_id` `app_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__gridbox_categories` CHANGE `description` `description` text;
ALTER TABLE `#__gridbox_categories` CHANGE `image` `image` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_categories` CHANGE `meta_title` `meta_title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_categories` CHANGE `meta_description` `meta_description` text;
ALTER TABLE `#__gridbox_categories` CHANGE `meta_keywords` `meta_keywords` text;
ALTER TABLE `#__gridbox_categories` CHANGE `share_title` `share_title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_categories` CHANGE `share_description` `share_description` text;
ALTER TABLE `#__gridbox_authors` CHANGE `title` `title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_authors` CHANGE `alias` `alias` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_authors` CHANGE `description` `description` text;
ALTER TABLE `#__gridbox_authors` CHANGE `image` `image` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_authors` CHANGE `meta_title` `meta_title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_authors` CHANGE `meta_description` `meta_description` text;
ALTER TABLE `#__gridbox_authors` CHANGE `meta_keywords` `meta_keywords` text;
ALTER TABLE `#__gridbox_authors` CHANGE `author_social` `author_social` text;
ALTER TABLE `#__gridbox_authors` CHANGE `share_title` `share_title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_authors` CHANGE `share_description` `share_description` text;
ALTER TABLE `#__gridbox_tags` CHANGE `title` `title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_tags` CHANGE `alias` `alias` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_tags` CHANGE `description` `description` text;
ALTER TABLE `#__gridbox_tags` CHANGE `image` `image` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_tags` CHANGE `meta_title` `meta_title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_tags` CHANGE `meta_description` `meta_description` text;
ALTER TABLE `#__gridbox_tags` CHANGE `meta_keywords` `meta_keywords` text;
ALTER TABLE `#__gridbox_tags` CHANGE `share_title` `share_title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_tags` CHANGE `share_description` `share_description` text;
ALTER TABLE `#__gridbox_tags_map` CHANGE `tag_id` `tag_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__gridbox_tags_map` CHANGE `page_id` `page_id` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__gridbox_custom_user_icons` CHANGE `title` `title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_custom_user_icons` CHANGE `group` `group` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_custom_user_icons` CHANGE `path` `path` varchar(255) NOT NULL DEFAULT "";