ALTER TABLE `#__gridbox_website` CHANGE `favicon` `favicon` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_website` CHANGE `header_code` `header_code` mediumtext;
ALTER TABLE `#__gridbox_website` CHANGE `body_code` `body_code` mediumtext;
ALTER TABLE `#__gridbox_website` CHANGE `breakpoints` `breakpoints` text;
ALTER TABLE `#__gridbox_website` CHANGE `canonical_domain` `canonical_domain` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_website` CHANGE `sitemap_domain` `sitemap_domain` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_website` CHANGE `comments_recaptcha` `comments_recaptcha` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_website` CHANGE `comments_facebook_login_key` `comments_facebook_login_key` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_website` CHANGE `comments_google_login_key` `comments_google_login_key` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_website` CHANGE `comments_vk_login_key` `comments_vk_login_key` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_website` CHANGE `reviews_admin_emails` `reviews_admin_emails` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_website` CHANGE `reviews_recaptcha` `reviews_recaptcha` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_website` CHANGE `reviews_facebook_login_key` `reviews_facebook_login_key` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_website` CHANGE `reviews_vk_login_key` `reviews_vk_login_key` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_fonts` CHANGE `custom_src` `custom_src` text;
ALTER TABLE `#__gridbox_fonts` CHANGE `font` `font` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_fonts` CHANGE `styles` `styles` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_plugins` CHANGE `title` `title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_plugins` CHANGE `image` `image` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_plugins` CHANGE `type` `type` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_plugins` CHANGE `joomla_constant` `joomla_constant` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_library` CHANGE `title` `title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_library` CHANGE `item` `item` mediumtext;
ALTER TABLE `#__gridbox_library` CHANGE `global_item` `global_item` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_library` CHANGE `image` `image` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_api` CHANGE `service` `service` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_api` CHANGE `key` `key` text;
ALTER TABLE `#__gridbox_filter_state` CHANGE `name` `name` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_filter_state` CHANGE `value` `value` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_filter_state` CHANGE `user` `user` int(11) NOT NULL DEFAULT 0;
ALTER TABLE `#__gridbox_weather` CHANGE `plugin_id` `plugin_id` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_weather` CHANGE `location` `location` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_weather` CHANGE `data` `data` mediumtext;
ALTER TABLE `#__gridbox_weather` CHANGE `saved_time` `saved_time` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_system_pages` CHANGE `title` `title` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_system_pages` CHANGE `type` `type` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_system_pages` CHANGE `theme` `theme` varchar(255) NOT NULL DEFAULT "";
ALTER TABLE `#__gridbox_system_pages` CHANGE `html` `html` mediumtext;
ALTER TABLE `#__gridbox_system_pages` CHANGE `items` `items` mediumtext;
ALTER TABLE `#__gridbox_system_pages` CHANGE `fonts` `fonts` text;
ALTER TABLE `#__gridbox_system_pages` CHANGE `page_options` `page_options` mediumtext;